[package]
name = "framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
reqwest-middleware = "0.1.6"
rvcr = "0.1.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
config-file = "0.2.3"
lazy_static = "1.4.0"
